var buttons_data =  [
    {"type": "action", "value":"C", "class":"btn btn-info clear "},
    {"type": "action", "value":"<|", "class":"btn btn-info clear "},
    {"type": "action", "value":"%", "class":"btn btn-primary allow_disable "},
    {"type": "action", "value":"/", "class":"btn btn-primary allow_disable "},
    {"type": "number", "value":"1", "class":"btn btn-default number "},
    {"type": "number", "value":"2", "class":"btn btn-default number "},
    {"type": "number", "value":"3", "class":"btn btn-default number "},
    {"type": "action", "value":"*", "class":"btn btn-primary allow_disable "},
    {"type": "number", "value":"4", "class":"btn btn-default number "},
    {"type": "number", "value":"5", "class":"btn btn-default number "},
    {"type": "number", "value":"6", "class":"btn btn-default number "},
    {"type": "action", "value":"+", "class":"btn btn-primary allow_disable "},
    {"type": "number", "value":"7", "class":"btn btn-default number "},
    {"type": "number", "value":"8", "class":"btn btn-default number "},
    {"type": "number", "value":"9", "class":"btn btn-default number "},
    {"type": "action", "value":"-", "class":"btn btn-primary allow_disable "},
    {"type": "action", "value":"+-", "class":"btn btn-default allow_disable "},
    {"type": "number", "value":"0", "class":"btn btn-default number "},
    {"type": "number", "value":".", "class":"btn btn-default number "},
    {"type": "action", "value":"=", "class":"btn btn-success allow_disable "}
];
