var buttons_data =  [
    {"type": "action", "value":"%", "class":"btn btn-primary btn-responsive"},
    {"type": "action", "value":"C", "class":"btn btn-primary btn-responsive"},
    {"type": "action", "value":"<|", "class":"btn btn-primary btn-responsive"},
    {"type": "action", "value":"/", "class":"btn btn-primary btn-responsive"},
    {"type": "number", "value":"1", "class":"btn btn-default btn-responsive"},
    {"type": "number", "value":"2", "class":"btn btn-default btn-responsive"},
    {"type": "number", "value":"3", "class":"btn btn-default btn-responsive"},
    {"type": "action", "value":"*", "class":"btn btn-primary btn-responsive"},
    {"type": "number", "value":"4", "class":"btn btn-default btn-responsive"},
    {"type": "number", "value":"5", "class":"btn btn-default btn-responsive"},
    {"type": "number", "value":"6", "class":"btn btn-default btn-responsive"},
    {"type": "action", "value":"+", "class":"btn btn-primary btn-responsive"},
    {"type": "number", "value":"7", "class":"btn btn-default btn-responsive"},
    {"type": "number", "value":"8", "class":"btn btn-default btn-responsive"},
    {"type": "number", "value":"9", "class":"btn btn-default btn-responsive"},
    {"type": "action", "value":"-", "class":"btn btn-primary btn-responsive"},
    {"type": "action", "value":"+-", "class":"btn btn-primary btn-responsive"},
    {"type": "number", "value":"0", "class":"btn btn-default btn-responsive"},
    {"type": "number", "value":".", "class":"btn btn-default btn-responsive"},
    {"type": "result", "value":"=", "class":"btn btn-success btn-responsive"}
];
